version: 2.1
jobs:
  build:
    working_directory: ~/cex-stock-checker
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build a docker image.
          command: |
            docker build \
              -t martinsirbe/cex-stock-checker:$(git rev-parse --short $CIRCLE_SHA1) \
              -t martinsirbe/cex-stock-checker:latest \
              -f Dockerfile .
      - run:
          name: Push the docker image to docker hub.
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push martinsirbe/cex-stock-checker:$(git rev-parse --short $CIRCLE_SHA1)
            docker push martinsirbe/cex-stock-checker:latest
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
  periodic-build:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
